name: Lint Jupyter Notebooks

on:
  push:
    paths:
      - '**.ipynb'
  pull_request:
    paths:
      - '**.ipynb'
jobs:
  nbqa-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install nbqa pylint

      - name: Run nbQA with pylint
        run: |
          nbqa pylint $(find . -name "*.ipynb")

      - name: Analysing the code with pylint
        run: |
          pylint **/*.py

